version: "3.8"

services:
  db:
    build:
      context: ./db  # Folder containing the Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    container_name: my-custom-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  api:
    build:
      context: ./api
    container_name: flask-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${FLASK_PORT}:5000"
    depends_on:
      - db
    volumes:
      - ./api:/app

  processor:
    build:
      context: ./processor
    container_name: data-processor
    environment:
      DATABASE_URL: ${DATABASE_URL}
      M1_DATA_DIR: ${M1_DATA_DIR}
      ACH_DATA_DIR: ${ACH_DATA_DIR}
    depends_on:
      - db
    volumes:
      - ./m1-data:${M1_DATA_DIR}
      - ./ach-data:${ACH_DATA_DIR}
    command: python process_files.py

volumes:
  pgdata:
    driver: local
